<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_d_RAD_SPLITTER_PANE_EXT_CONTENT_ctl0_838ae3</name>
   <tag></tag>
   <elementGuidId>81b45908-17f2-4518-bc68-9ef323e172c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='RAD_SPLITTER_PANE_EXT_CONTENT_ctl00_ctl00_PageBody_Contenuto_TreeStruttura']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RAD_SPLITTER_PANE_EXT_CONTENT_ctl00_ctl00_PageBody_Contenuto_TreeStruttura</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;ctl00_ctl00_PageBody_Contenuto_TreeStruttura&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>899b8d0e-169e-4ce7-92b5-7837a3691182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00_ctl00_PageBody_Contenuto_TreeStruttura</value>
      <webElementGuid>78f287ec-8659-4fb4-9bd5-bfffaed57f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RAD_SPLITTER_PANE_EXT_CONTENT_ctl00_ctl00_PageBody_Contenuto_TreeStruttura</value>
      <webElementGuid>ca8dc092-49f6-4b29-a62c-c96db8402165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Aspx/TML/StrutturaOrganizzativa/StrutturaOrganizzativa_Tree_Panel.aspx?PIV=6&amp;Xml=Aspx/TML/StrutturaOrganizzativa/StrutturaOrganizzativa_Tree_Panel&amp;DataRiferimento=2026-01-22&amp;OpenId=&amp;PUI=cdbb508fad954f05bef6b4ab1bac6f10</value>
      <webElementGuid>a7fde591-948f-4dfc-8a4b-f8949e3538c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>918df8d0-e06a-4bbd-b93b-6e02bca4ed04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f2c8c3da-268f-4053-8c85-e0b45e2d8289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RAD_SPLITTER_PANE_EXT_CONTENT_ctl00_ctl00_PageBody_Contenuto_TreeStruttura&quot;)</value>
      <webElementGuid>539b3b17-8a68-4bb6-929a-57ead083fb6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='RAD_SPLITTER_PANE_EXT_CONTENT_ctl00_ctl00_PageBody_Contenuto_TreeStruttura']</value>
      <webElementGuid>e81fcd79-6b26-41db-85c3-159ab7e898fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RAD_SPLITTER_PANE_CONTENT_ctl00_ctl00_PageBody_Contenuto_TreeStruttura']/iframe</value>
      <webElementGuid>844b8b2b-0508-4c7a-b895-4259c205b138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a44c1ec6-55fe-40cf-b0e9-7bf9145cb48a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'ctl00_ctl00_PageBody_Contenuto_TreeStruttura' and @id = 'RAD_SPLITTER_PANE_EXT_CONTENT_ctl00_ctl00_PageBody_Contenuto_TreeStruttura' and @src = '/Aspx/TML/StrutturaOrganizzativa/StrutturaOrganizzativa_Tree_Panel.aspx?PIV=6&amp;Xml=Aspx/TML/StrutturaOrganizzativa/StrutturaOrganizzativa_Tree_Panel&amp;DataRiferimento=2026-01-22&amp;OpenId=&amp;PUI=cdbb508fad954f05bef6b4ab1bac6f10']</value>
      <webElementGuid>4510772f-208f-4ea2-a22c-7b0bf9ead4bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
