<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_ctl00_ctl00_PageBody_Contenu_9644f0</name>
   <tag></tag>
   <elementGuidId>b3dda77c-f926-4373-b85e-a704bd78166d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_btnSalva']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_PageBody_Contenuto_ALVForm1_btnSalva</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cea44fc-c11c-4cd3-929d-e0cb30a6248c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e4dae1b7-45ab-418f-8521-544e90d77ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$PageBody$Contenuto$ALVForm1$btnSalva</value>
      <webElementGuid>33b3eed8-7445-43a8-ac24-7a7a35c5d1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>33e7772d-b46e-4b26-9c71-ac4789842c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:WebForm_DoPostBackWithOptions(new WebForm_PostBackOptions(&quot;ctl00$ctl00$PageBody$Contenuto$ALVForm1$btnSalva&quot;, &quot;&quot;, true, &quot;&quot;, &quot;&quot;, false, false))</value>
      <webElementGuid>46b15b36-c5d6-4a70-808e-13a56e1861f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_PageBody_Contenuto_ALVForm1_btnSalva</value>
      <webElementGuid>708a9f54-0e9a-44b8-a35f-94fcb3db2c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-normal</value>
      <webElementGuid>6ccbe202-8fcc-4553-8e16-e124d5b5e683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_PageBody_Contenuto_ALVForm1_btnSalva&quot;)</value>
      <webElementGuid>e5d3e115-6729-4d1a-9c7e-4c8d844c6960</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_btnSalva']</value>
      <webElementGuid>efb6dd16-c6e1-465e-ab32-f6c011571ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_buttonRow']/input</value>
      <webElementGuid>6a4396c1-b674-4e37-80c3-4d224ec6ddc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e1e76ad0-3d62-4857-bbd6-2fb7566c31cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$ctl00$PageBody$Contenuto$ALVForm1$btnSalva' and @id = 'ctl00_ctl00_PageBody_Contenuto_ALVForm1_btnSalva']</value>
      <webElementGuid>aa4863d7-fbc9-4e9f-a25e-5faf683e6078</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
