<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_ctl00_ctl00_PageBody_Contenu_b04958</name>
   <tag></tag>
   <elementGuidId>3c787876-acda-4832-ad75-f50d5075d12b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl01_Username']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl01_Username</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl01_Username</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b9776c2e-68f7-4666-ab3d-4d6f8ef283b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$PageBody$Contenuto$ALVForm1$ctl01$Username</value>
      <webElementGuid>346c490b-845b-4f95-96ed-61adccdd8769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>646ff7d6-0c95-4421-ab74-facdf9fa2bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>d2f508f2-8973-4a3c-b437-2b82ff4e0366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl01_Username</value>
      <webElementGuid>29d9d09f-bc6d-450e-8b1a-7b93c644f625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-normal</value>
      <webElementGuid>8fe5a9da-065b-4d13-a8bb-7b45753a31b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl01_Username&quot;)</value>
      <webElementGuid>bccd5304-bc61-426e-bcc6-d7ccb226beed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl01_Username']</value>
      <webElementGuid>800559ae-ae13-490c-a174-0297a0cd425e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_userRow']/div/div[2]/input</value>
      <webElementGuid>c91db885-5b1c-474c-b973-d8f4221ca39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/input</value>
      <webElementGuid>c9e4b3ab-1b53-4ce2-b370-82a411915b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$PageBody$Contenuto$ALVForm1$ctl01$Username' and @type = 'text' and @id = 'ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl01_Username']</value>
      <webElementGuid>f77ee79b-c8ca-4c79-b948-4efbfde9828c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
