<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_ctl00_ctl00_PageBody_Contenu_40ebb5</name>
   <tag></tag>
   <elementGuidId>ac257d1c-44d8-4eed-b11e-27614465074e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl03_Password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl03_Password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl03_Password</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>356bf0d1-52d2-4f16-9d00-78a71935ada2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$PageBody$Contenuto$ALVForm1$ctl03$Password</value>
      <webElementGuid>2839f5f6-427b-4b3d-8d83-0946d678772c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>aa37c735-c5f3-4216-915b-b5b2524b2433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>24cf39ef-e918-4287-8ac3-45e644ec1a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl03_Password</value>
      <webElementGuid>553a80e5-2e32-43ea-aef3-767789e1c8e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-normal</value>
      <webElementGuid>0aefe550-f7d6-45f1-a4ce-10b7d084d789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bb088153-16d4-4ea7-9b4b-a6d3e8aaf729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl03_Password&quot;)</value>
      <webElementGuid>e29e1b35-2d45-483b-9b57-54a2fab82182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl03_Password']</value>
      <webElementGuid>bab0d7bd-7299-4960-a1ba-c43c31067d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ctl00_PageBody_Contenuto_ALVForm1_passwordRow']/div/div[2]/input</value>
      <webElementGuid>35cb7787-33de-4c08-8b53-594cd2bea285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>5628eb5c-b88c-4107-bcfd-9564bc4df016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ctl00$PageBody$Contenuto$ALVForm1$ctl03$Password' and @type = 'password' and @id = 'ctl00_ctl00_PageBody_Contenuto_ALVForm1_ctl03_Password']</value>
      <webElementGuid>52a1b765-06d0-4330-8501-81472f1616a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
